version: '2.1'

networks:
  fabric:
    external:
      name: fabric

services:
  explorer-db:
    image: hyperledger/explorer-db
    container_name: explorer-db
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U hppoc"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fabric

  explorer:
    image: hyperledger/explorer
    container_name: explorer
    environment:
      - DATABASE_HOST=explorer-db
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
      - DISCOVERY_AS_LOCALHOST=false
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile.json:/opt/explorer/app/platform/fabric/connection-profile.json
      - ../organizations:/tmp/crypto
    ports:
      - "9090:8080"
    depends_on:
      explorer-db:
        condition: service_healthy
    networks:
      - fabric

volumes:
  pgdata:
